import Vue from 'vue'
import {
    ActionSheet,
    Button,
    Card,
    Cell,
    CellGroup,
    Checkbox,
    CheckboxGroup,
    Col,
    Collapse,
    CollapseItem,
    CountDown,
    DatetimePicker,
    Dialog,
    Divider,
    DropdownItem,
    DropdownMenu,
    Field,
    Form,
    Grid,
    GridItem,
    Icon,
    Image as VanImage,
    Lazyload,
    List,
    Loading,
    NavBar,
    NoticeBar,
    NumberKeyboard,
    Overlay,
    PasswordInput,
    Picker,
    Popup,
    PullRefresh,
    Radio,
    RadioGroup,
    Row,
    Sidebar,
    SidebarItem,
    Slider,
    Step,
    Stepper,
    Steps,
    Sticky,
    Swipe,
    SwipeItem,
    Switch,
    Search,
    Tab,
    Tabbar,
    TabbarItem,
    Tabs,
    Toast,
    Uploader
} from 'vant'

Vue.use(Step)
Vue.use(Steps)
Vue.use(Divider)
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(NoticeBar)
Vue.use(Icon)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Stepper)
Vue.use(Lazyload)
    .use(CheckboxGroup)
    .use(Checkbox)
    .use(NavBar)
    .use(Sticky)
    .use(Form)
    .use(Field)
    .use(VanImage)
    .use(Cell)
    .use(CellGroup)
    .use(Card)
    .use(Toast)
    .use(Dialog)
    .use(Tab)
    .use(Tabs)
    .use(Sidebar)
    .use(SidebarItem)
    .use(PullRefresh)
    .use(List)
    .use(DatetimePicker)
    .use(Overlay)
    .use(PasswordInput)
    .use(NumberKeyboard)
    .use(Collapse)
    .use(CollapseItem)
    .use(Row)
    .use(Col)
    .use(Radio)
    .use(RadioGroup)
    .use(Uploader)
    .use(ActionSheet)
    .use(Picker)
    .use(Popup)
    .use(Loading)
    .use(DropdownMenu)
    .use(DropdownItem)
    .use(CountDown)
    .use(Slider)
    .use(Switch)
    .use(Search)
